# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativebaseKitchenSink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativebaseKitchenSink
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'


end
